[project]
name = 'contract'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.opengov]
path = 'contracts/opengov.clar'
clarity_version = 2
epoch = 2.4

[contracts.opengov-main]
path = 'contracts/opengov-main.clar'
clarity_version = 2
epoch = 2.4

[contracts.test]
path = 'contracts/test.clar'
clarity_version = 2
epoch = 2.4
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
